
// FETCH FLYER (ASYNC)
export const FETCH_FLYER_REQUEST = 'FETCH_FLYER_REQUEST';
export const FETCH_FLYER_SUCCESS = 'FETCH_FLYER_SUCCESS';
export const FETCH_FLYER_FAIL = 'FETCH_FLYER_FAIL';

// SAVE FLYER (ASYNC)
export const SAVE_FLYER_REQUEST = 'SAVE_FLYER_REQUEST';
export const SAVE_FLYER_SUCCESS = 'SAVE_FLYER_SUCCESS';
export const SAVE_FLYER_FAIL = 'SAVE_FLYER_FAIL';

// WIDGET ADD\DELETE (ASYNC?)
export const ADD_WIDGET = 'ADD_WIDGET';
export const DELETE_WIDGET = 'DELETE_WIDGET';

// WIDGET MOVE\OPEN\CLOSE\SAVE (ASYNC?)
export const MOVE_WIDGET = 'MOVE_WIDGET';
export const OPEN_WIDGET_EDIT = 'OPEN_WIDGET_EDIT';
export const CLOSE_WIDGET_EDIT = 'CLOSE_WIDGET_EDIT';
export const SAVE_WIDGET = 'SAVE_WIDGET';

// PANEL
export const SHOW_ADDING_PANEL = 'SHOW_ADDING_PANEL';
export const HIDE_ADDING_PANEL = 'HIDE_ADDING_PANEL';

// FETCH FLYER INFO
export const FETCH_FLYER_INFO_REQUEST = 'FETCH_FLYER_INFO_REQUEST';
export const FETCH_FLYER_INFO_SUCCESS = 'FETCH_FLYER_INFO_SUCCESS';
export const FETCH_FLYER_INFO_FAIL = 'FETCH_FLYER_INFO_FAIL';

// FETCH POSSIBLE SETTINGS
export const FETCH_POSSIBLE_SETTINGS_REQUEST = 'FETCH_POSSIBLE_SETTINGS_REQUEST';
export const FETCH_POSSIBLE_SETTINGS_SUCCESS = 'FETCH_POSSIBLE_SETTINGS_SUCCESS';
export const FETCH_POSSIBLE_SETTINGS_FAIL = 'FETCH_POSSIBLE_SETTINGS_FAIL';
