
// FETCH FLYER (ASYNC)
export const FETCH_FLYER_REQUEST = 'FETCH_FLYER_REQUEST';
export const FETCH_FLYER_SUCCESS = 'FETCH_FLYER_SUCCESS';
export const FETCH_FLYER_FAILURE = 'FETCH_FLYER_FAILURE';

// SAVE FLYER (ASYNC)
export const SAVE_FLYER_REQUEST = 'SAVE_FLYER_REQUEST';
export const SAVE_FLYER_SUCCESS = 'SAVE_FLYER_SUCCESS';
export const SAVE_FLYER_FAILURE = 'SAVE_FLYER_FAILURE';

// WIDGET ADD\DELETE
export const ADD_WIDGET = 'ADD_WIDGET';
export const DELETE_WIDGET = 'DELETE_WIDGET';

// WIDGET MOVE\OPEN\CLOSE\SAVE
export const MOVE_WIDGET = 'MOVE_WIDGET';
export const OPEN_WIDGET_EDIT = 'OPEN_WIDGET_EDIT';
export const CLOSE_WIDGET_EDIT = 'CLOSE_WIDGET_EDIT';
export const SAVE_WIDGET = 'SAVE_WIDGET';

// PANEL
export const SHOW_ADDING_PANEL = 'SHOW_ADDING_PANEL';
export const HIDE_ADDING_PANEL = 'HIDE_ADDING_PANEL';

// FETCH FLYER INFO (ASYNC)
export const FETCH_FLYER_INFO_REQUEST = 'FETCH_FLYER_INFO_REQUEST';
export const FETCH_FLYER_INFO_SUCCESS = 'FETCH_FLYER_INFO_SUCCESS';
export const FETCH_FLYER_INFO_FAILURE = 'FETCH_FLYER_INFO_FAILURE';

// FETCH POSSIBLE SETTINGS (ASYNC)
export const FETCH_POSSIBLE_SETTINGS_REQUEST = 'FETCH_POSSIBLE_SETTINGS_REQUEST';
export const FETCH_POSSIBLE_SETTINGS_SUCCESS = 'FETCH_POSSIBLE_SETTINGS_SUCCESS';
export const FETCH_POSSIBLE_SETTINGS_FAILURE = 'FETCH_POSSIBLE_SETTINGS_FAILURE';

// FLYER SETTINGS CHANGE
export const CHANGE_FLYER_BACKGROUND = 'CHANGE_FLYER_BACKGROUND';
export const CHANGE_FLYER_COLOR = 'CHANGE_FLYER_COLOR';
export const CHANGE_FLYER_FONT = 'CHANGE_FLYER_FONT';
export const CHANGE_FLYER_THEME = 'CHANGE_FLYER_THEME';
