
// FETCH (ASYNC)
export const FETCH_FLYER_REQUEST = 'FETCH_FLYER_REQUEST';
export const FETCH_FLYER_SUCCESS = 'FETCH_FLYER_SUCCESS';
export const FETCH_FLYER_FAIL = 'FETCH_FLYER_FAIL';

// SAVE (ASYNC)
export const SAVE_FLYER_REQUEST = 'SAVE_FLYER_REQUEST';
export const SAVE_FLYER_SUCCESS = 'SAVE_FLYER_SUCCESS';
export const SAVE_FLYER_FAIL = 'SAVE_FLYER_FAIL';

// WIDGET ADD\DELETE
export const ADD_WIDGET = 'ADD_WIDGET';
export const DELETE_WIDGET = 'DELETE_WIDGET';

// WIDGET MOVE\OPEN_TO_EDIT\CLOSE
export const MOVE_WIDGET = 'MOVE_WIDGET';
export const OPEN_WIDGET_EDIT = 'OPEN_WIDGET_EDIT';
export const CLOSE_WIDGET_EDIT = 'CLOSE_WIDGET_EDIT';
export const SAVE_WIDGET = 'SAVE_WIDGET';

// PANEL
export const SHOW_PANEL = 'SHOW_PANEL';
export const HIDE_PANEL = 'HIDE_PANEL';
