
// FETCH (ASYNC)
export const FETCH_FLYER_REQUEST = 'FETCH_FLYER_REQUEST';
export const FETCH_FLYER_SUCCESS = 'FETCH_FLYER_SUCCESS';
export const FETCH_FLYER_FAIL = 'FETCH_FLYER_FAIL';

// SAVE (ASYNC)
export const SAVE_FLYER_REQUEST = 'SAVE_FLYER_REQUEST';
export const SAVE_FLYER_SUCCESS = 'SAVE_FLYER_SUCCESS';
export const SAVE_FLYER_FAIL = 'SAVE_FLYER_FAIL';

// WIDGET
export const ADD_WIDGET = 'ADD_WIDGET';
export const DELETE_WIDGET = 'DELETE_WIDGET';
export const MOVE_WIDGET = 'MOVE_WIDGET';

// PANEL
export const SHOW_PANEL = 'SHOW_PANEL';
export const HIDE_PANEL = 'HIDE_PANEL';
